theme: minima
title: Infos zur &Uuml;bungsgruppe 4 
description: Hier gibt es eine grobe &Uuml;bersicht &uuml;ber die Themen und zus&auml;tzliche Materialien. Wenn ich etwas hier hochlade, k&uuml;ndige ich es immer per Email an.

show_downloads: false
